name: jam-build-container
services:
  # The app
  jam-build:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        AUTHZ_URL: ${AUTHZ_URL}
        AUTHZ_CLIENT_ID: ${AUTHZ_CLIENT_ID}
    image: jam-build:latest
    environment:
      DB_HOST: mariadb
      DB_DATABASE: jam_build
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_APP_USER: ${DB_APP_USER}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      AUTHZ_URL: http://authorizer:9010
      AUTHZ_CLIENT_ID: ${AUTHZ_CLIENT_ID}
    depends_on:
      - mariadb
      - authorizer
    ports:
      - 5000:5000
    networks:
      - backend
    # setup demo users and data
    #post_start:
    #  - command: ['apt-get', 'install', '-y', 'libnspr4', 'libnss3', 'libdbus-1-3', 'libatk1.0-0', 'libatspi2.0-0', 'libxcomposite1', 'libxdamage1', 'libxfixes3', 'libxrandr2', 'libgbm1', 'libxkbcommon0', 'libasound2', 'libatk-bridge2.0-0', 'libcups2']
    #    user: root
    #    privileged: true
    #  - command: ['npx', 'playwright', 'install', 'chromium']
    #    working_dir: '/home/node/app'
    #  - command: ['npm', 'run', 'test:local:api']
    #    working_dir: '/home/node/app'
    #    environment:
    #      - AUTHZ_URL=http://authorizer:9010
    #      - BASE_URL=http://jam-build:5000
    #      - AUTHZ_CLIENT_ID=${AUTHZ_CLIENT_ID}
    #      - DEBUG=test:*

  # The cache
  cache:
    image: redis:7.4.6
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - backend
  
  # The authorizer
  authorizer:
    image: localnerve/authorizer:v1.5.2
    environment:
      ENV: production
      ADMIN_SECRET: ${AUTHZ_ADMIN_SECRET}
      DATABASE_TYPE: mariadb
      DATABASE_URL: root:${DB_ROOT_PASSWORD}@tcp(mariadb:3306)/authorizer
      DATABASE_NAME: authorizer
      CLIENT_ID: ${AUTHZ_CLIENT_ID}
      ORGANIZATION_NAME: ${AUTHZ_ORGANIZATION_NAME}
      ORGANIZATION_LOGO: ${AUTHZ_ORGANIZATION_LOGO}
      ROLES: 'admin,user'
      PORT: 9010
      REDIS_URL: redis://cache:6379
  #   SMTP_HOST: ${AUTHZ_SMTP_HOST}
  #   SMTP_PORT: ${AUTHZ_SMTP_PORT}
  #   SMTP_USER: ${AUTHZ_SMTP_USER}
  #   SMTP_PASSWORD: ${AUTHZ_SMTP_PASSWORD}
  #   SENDER_EMAIL: ${AUTHZ_SENDER_EMAIL}
    depends_on:
      mariadb:
        condition: service_healthy
      cache:
        condition: service_started
    ports:
      - 9010:9010
    networks:
      - backend

  # The database
  mariadb:
    image: mariadb:11.8.3
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DATABASE: jam_build
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_APP_USER: ${DB_APP_USER}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./data/database/mariadb-ddl-init.sh:/docker-entrypoint-initdb.d/1.sh
      - ./data/database/mariadb-ddl-tables.sql:/docker-entrypoint-initdb.d/2.sql
      - ./data/database/mariadb-ddl-procedures.sql:/docker-entrypoint-initdb.d/3.sql
      - ./data/database/mariadb-ddl-privileges.sql:/docker-entrypoint-initdb.d/4.sql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin -u root --password=$DB_ROOT_PASSWORD ping -h localhost"]
      timeout: 20s
      retries: 10
    networks:
      - backend

  # The database backup command
  backup:
    image: mariadb:11.8.3
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - backup:/backup
    networks:
      - backend
    entrypoint: ["/bin/sh"]
    command: ["-c", "mariadb-dump -h mariadb -u root --password=\"$DB_ROOT_PASSWORD\" --all-databases > /backup/db-$(date +%Y%m%d-%H%M%S).sql && tar -czf /backup/db-$(date +%Y%m%d-%H%M%S).tar.gz -C /backup db-$(date +%Y%m%d-%H%M%S).sql --remove-files && echo 'Backup complete: db-'$(date +%Y%m%d-%H%M%S).tar.gz"]
    profiles:
      - tools

  # Extract backups to local bind mount
  extract-backup:
    image: alpine:latest
    volumes:
      - backup:/source
      - ./volumes/backup:/dest
    entrypoint: ["/bin/sh"]
    command: ["-c", "cp -av /source/* /dest/ && echo 'Backup files extracted to ./volumes/backup'"]
    profiles:
      - tools

  # The database hydration command
  hydrate:
    image: mariadb:11.8.3
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      BACKUP_FILE: ${BACKUP_FILE:-latest}  # Specify backup file or 'latest'
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - backup:/backup
    networks:
      - backend
    entrypoint: ["/bin/sh"]
    command:
      - "-c"
      - |
        set -e
        echo "Starting database restore..."
        
        # Find the backup file
        if [ "$BACKUP_FILE" = "latest" ]; then
          BACKUP_FILE=$(ls -t /backup/db-*.tar.gz 2>/dev/null | head -n1)
          if [ -z "$BACKUP_FILE" ]; then
            echo "Error: No backup files found in /backup/"
            exit 1
          fi
          echo "Using latest backup: $BACKUP_FILE"
        else
          BACKUP_FILE="/backup/$BACKUP_FILE"
          if [ ! -f "$BACKUP_FILE" ]; then
            echo "Error: Backup file not found: $BACKUP_FILE"
            exit 1
          fi
        fi
        
        # Extract the backup
        echo "Extracting backup..."
        tar -xzf "$BACKUP_FILE" -C /backup
        SQL_FILE=$(tar -tzf "$BACKUP_FILE" | head -n1)
        
        # Drop all databases except system databases
        echo "Dropping existing databases..."
        mariadb -h mariadb -u root --password="$DB_ROOT_PASSWORD" \
          -e "SELECT CONCAT('DROP DATABASE IF EXISTS \`', schema_name, '\`;') 
              FROM information_schema.schemata 
              WHERE schema_name NOT IN ('information_schema', 'mysql', 'performance_schema', 'sys')" \
          -sN | mariadb -h mariadb -u root --password="$DB_ROOT_PASSWORD"
        
        # Restore from backup
        echo "Restoring databases from $SQL_FILE..."
        mariadb -h mariadb -u root --password="$DB_ROOT_PASSWORD" < "/backup/$SQL_FILE"
        
        # Cleanup extracted SQL file
        rm -f "/backup/$SQL_FILE"
        
        echo "Database restore complete!"
    profiles:
      - tools

volumes:
  dbdata:
  backup:
  cache:

networks:
  backend:
    driver: bridge
